type MaybeRef<T> = T | Ref<T> | ComputedRef<T>

type Fallback = {
  title?: string
  description?: string
  image?: string
  canonical?: string
}

/**
 * Composable para configurar SEO dinámico desde Directus
 *
 * @param seoInput - Objeto SEO de Directus con campos:
 *   - meta_title: Título de la página
 *   - meta_description: Descripción meta
 *   - og_image: ID de imagen de Directus para Open Graph
 *   - canonical_url: URL canónica (opcional, se auto-genera si no existe)
 *   - robots_index: Boolean - true para indexar, false para noindex
 *   - robots_follow: Boolean - true para follow, false para nofollow
 *   - meta_additional_fields: Objeto con meta tags adicionales
 *
 * @param fallbackInput - Valores fallback si Directus no tiene datos
 */
export function useDirectusSeo(seoInput?: MaybeRef<any>, fallbackInput?: MaybeRef<Fallback>) {
  const seo = computed(() => (unref(seoInput) as any) || {})
  const fb = computed(() => (unref(fallbackInput) as Fallback) || {})
  const route = useRoute()
  const config = useRuntimeConfig()

  // ===== Campos básicos =====
  const title = computed(() => seo.value?.meta_title || fb.value.title || 'ConCentra')
  const description = computed(() => seo.value?.meta_description || fb.value.description || '')

  // ===== Open Graph Image =====
  const ogImageUrl = computed(() => {
    const imageId = seo.value?.og_image
    if (imageId) {
      // Generar URL de Directus optimizada para OG (1200x630)
      return `${config.public.directusUrl}/assets/${imageId}?format=webp&width=1200&height=630&fit=cover`
    }
    return fb.value.image || ''
  })

  // ===== Robots meta =====
  const robots = computed(() => {
    // CORRECCIÓN: Lógica invertida - robots_index=true significa indexar
    const shouldIndex = seo.value?.robots_index !== false // Default: true
    const shouldFollow = seo.value?.robots_follow !== false // Default: true
    const parts = [
      shouldIndex ? 'index' : 'noindex',
      shouldFollow ? 'follow' : 'nofollow'
    ]
    return parts.join(', ')
  })

  // ===== Canonical URL con auto-generación =====
  const canonical = computed(() => {
    const fromDirectus = seo.value?.canonical_url
    const fromFallback = fb.value.canonical
    const siteUrl = config.public.siteUrl || 'https://concentra.com.do'
    const autoGenerated = `${siteUrl}${route.path}`

    return fromDirectus || fromFallback || autoGenerated
  })

  // ===== Meta tags principales =====
  useHead({
    title,
    meta: [
      // Basic meta
      { name: 'description', content: description },
      { name: 'robots', content: robots },

      // Open Graph (Facebook, LinkedIn, WhatsApp)
      { property: 'og:title', content: title },
      { property: 'og:description', content: description },
      { property: 'og:image', content: ogImageUrl },
      { property: 'og:image:width', content: '1200' },
      { property: 'og:image:height', content: '630' },
      { property: 'og:image:type', content: 'image/webp' },
      { property: 'og:type', content: 'website' },
      { property: 'og:url', content: canonical },
      { property: 'og:site_name', content: 'ConCentra' },
      { property: 'og:locale', content: 'es_DO' },

      // Twitter Cards
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:title', content: title },
      { name: 'twitter:description', content: description },
      { name: 'twitter:image', content: ogImageUrl },
      { name: 'twitter:site', content: '@ConCentraRD' }, // Ajustar con handle real
    ],
    link: [
      { rel: 'canonical', href: canonical as any },
    ],
  })

  // ===== Meta tags adicionales con validación =====
  const ALLOWED_META_NAMES = [
    'author', 'keywords', 'generator', 'theme-color',
    'application-name', 'apple-mobile-web-app-title'
  ]

  const additional = computed(() => seo.value?.meta_additional_fields || {})
  const additionalMeta = computed(() => {
    const out: { name: string; content: string }[] = []
    for (const [k, v] of Object.entries(additional.value)) {
      // Validar que el nombre del meta tag sea permitido
      if (!ALLOWED_META_NAMES.includes(k)) continue
      if (v == null) continue
      out.push({ name: String(k), content: String(v) })
    }
    return out
  })

  if (additionalMeta.value.length > 0) {
    useHead({
      meta: additionalMeta as any,
    })
  }
}

