export const clients = [
  {
    nombre: "AFP Siembra",
    logo: "https://concentra.com.do/images/clientes/42.jpg",
    segmento: "Seguros",
    productos: "SysAid",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },
  {
    nombre: "Banco BHD",
    logo: "https://concentra.com.do/images/clientes/41.jpg",
    segmento: "Bancos y Servicios Financieros",
    productos: "Outsourcing",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },
  {
    nombre: "Banreservas",
    logo: "https://concentra.com.do/images/clientes/40.jpg",
    segmento: "Bancos y Servicios Financieros",
    productos: "Ciberseguridad",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },
  {
    nombre: "Banco Popular Dominicano",
    logo: "https://concentra.com.do/images/clientes/42.jpg",
    segmento: "Bancos y Servicios Financieros",
    productos: "Consultoría ITIL",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },
  {
    nombre: "Banco Santa Cruz",
    logo: "https://concentra.com.do/images/clientes/2.jpg",
    segmento: "Bancos y Servicios Financieros",
    productos: "Consultoría ITIL",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },
  {
    nombre: "Bolsa de Valores de la RD",
    logo: "https://concentra.com.do/images/clientes/3.jpg",
    segmento: "Bancos y Servicios Financieros",
    productos: "SoftExpert",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },
  {
    nombre: "ProDominicana",
    logo: "https://concentra.com.do/images/clientes/4.jpg",
    segmento: "Gobierno y Sector Público",
    productos: "SoftExpert",
    pais: "Rep. Dom",
    vendedor: "INNOVX SRL",
  },
  {
    nombre: "Claro Dominicana",
    logo: "https://concentra.com.do/images/clientes/5.jpg",
    segmento: "Telecomunicaciones",
    productos: "Outsourcing",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },
  {
    nombre: "DGII",
    logo: "https://concentra.com.do/images/clientes/6.jpg",
    segmento: "Gobierno y Sector Público",
    productos: "Desarrollo de Software, Varonis",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },
  {
    nombre: "EDE Este",
    logo: "https://concentra.com.do/images/clientes/7.jpg",
    segmento: "Energía",
    productos: "Consultoría ITIL, SoftExpert",
    pais: "Rep. Dom",
    vendedor: "Concentra SRL",
  },

  /* … resto … */
];
